# Numpy

In [1]:
# Load the library
import numpy as np
print(np.__version__)

1.16.2


In [2]:
# Create a vector
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [3]:
# Create a matrix
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [4]:
# Get the dimensions of a matrix
matrix.shape

(2, 2)

In [5]:
# Get the number of elements (rows * cols)
matrix.size

4

In [6]:
# Get the number of dimensions
matrix.ndim

2

In [7]:
# Apply a function to a matrix
matrix = np.array([[1,2],[3,4]])

# Create a function
add_10 = lambda x: x + 10

# Create a vertorized version of the function
vectorized_add_10 = np.vectorize(add_10)

# Apply this function to a matrix
vectorized_add_10(matrix)

array([[11, 12],
       [13, 14]])

In [8]:
# Max
np.max(matrix)

4

In [9]:
# Min
np.min(matrix)

1

In [10]:
# Mean
np.mean(matrix)

2.5

In [11]:
# Variance
np.var(matrix)

1.25

In [12]:
# Standard deviation
np.std(matrix)

1.118033988749895

In [13]:
# Reshape a matrix
matrix.reshape(1,4)

array([[1, 2, 3, 4]])

In [14]:
matrix.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
matrix.reshape(4,-1) # -1 means 'as many as needed'

array([[1],
       [2],
       [3],
       [4]])

In [16]:
# Transpose
matrix.T

array([[1, 3],
       [2, 4]])

In [17]:
# Flatten a matrix
matrix.flatten()

array([1, 2, 3, 4])

In [18]:
# Diagonal of a matrix
matrix.diagonal()

array([1, 4])

In [19]:
# Trace
matrix.trace()

5

In [20]:
# Rank of a matrix
np.linalg.matrix_rank(matrix)

2

In [21]:
# Determinant
np.linalg.det(matrix)

-2.0000000000000004

In [22]:
# Eigenvalues and eigenvectors
eigenval,eigenvec = np.linalg.eig(matrix)

print(eigenval)
print(' ')
print(eigenvec)

[-0.37228132  5.37228132]
 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [23]:
# Dot product
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.dot(v1, v2)

32

In [24]:
# @ operator = dot product
v1 @ v2

32

In [25]:
# Element-wise multiplication
v1 * v2

array([ 4, 10, 18])

In [26]:
# Matrix inverse
np.linalg.inv(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [27]:
# Check
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [28]:
# If the matrix is sparse (i.e. very few non-zero values),
# we can use a compressed sparse row (CSR) matrix to store its values
matrix = np.array([[1,0,0,0,0,0,0,0,0,0], [0,1,0,0,0,0,0,0,0,0]])

from scipy import sparse
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (0, 0)	1
  (1, 1)	1
